### PR TITLE
Add Map instance

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by wodeni** [comment]
Trying to use this library to emit TS types for a large record that has `Map`s in there as well (from `Data.Map.Strict` in my case`), which is supported by Aeson by default. Is there any chance to merge this? 

If not, any advice on how to manually derive a `TypeScript` instance for `Map` in our own code?

**Comment by thomasjm** [comment]
Hi @wodeni -- I'd like to merge this but it's a breaking change, so I've been waiting for a convenient time to do a major version bump.

You can just take the instance from this PR and put it somewhere in your code (my own projects do this too):

```haskell
instance (TypeScript a, TypeScript b) => TypeScript (Map a b) where
  getTypeScriptType _ = [i|{[k: #{getTypeScriptType (Proxy :: Proxy a)}]: #{getTypeScriptType (Proxy :: Proxy b)}}|]
```

**Comment by wodeni** [comment]
Thanks for the quick reply! 

I'm new to quasiquoting in Haskell, so I was a little confused by the syntax `[i|{[k: #{getTypeScriptType (Proxy :: Proxy a)}]: #{getTypeScriptType (Proxy :: Proxy b)}}|]`. I kept getting "`i` is not in scope" errors. Is `i` something defined in this or some other library?

**Comment by hasufell** [comment]
You can use the fork at https://github.com/capital-match/aeson-typescript which includes other improvements.

**Comment by thomasjm** [comment]
@wodeni `i` is from the `interpolate` package and it's just used to make string interpolation easier. You can do the same thing using manual string concatenation or whatever if you prefer. I usually import [Data.String.Interpolate.IsString](http://hackage.haskell.org/package/interpolate-0.2.0/docs/Data-String-Interpolate-IsString.html). You'll also need the `QuasiQuotes` extension turned on like you mentioned.

**Comment by wodeni** [comment]
Thanks @thomasjm for explaining! This makes much more sense now. I was able to just use string concatenation to construct my types but good to know where `i` came from.

**Pull request closed without merging**
